package com.silence.domain;

import jakarta.persistence.*;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents a single journal entry in the SILENCE system.
 * The entry is limited in length and tied to a unique date to ensure
 * the "one entry per day" constraint at the database level.
 */
@Entity
@Table(name = "entries")
public class Entry {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The core thought of the user. Limited to 300 characters
     * to encourage brevity and intentionality.
     */
    @Column(nullable = false, length = 300)
    @Size(max = 300, message = "Entry cannot exceed 300 characters")
    private String content;

    /**
     * The date this entry was written.
     * Marked as unique to enforce the "Anti-Social" one-entry-per-day rule.
     */
    @Column(nullable = false, unique = true)
    private LocalDate entryDate;

    /**
     * Precise timestamp for audit and visual "erosion" calculations.
     */
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Subtle feedback generated by the AI "Silent Observer".
     */
    @Column(columnDefinition = "TEXT")
    private String aiFeedback;

    /**
     * Numerical representation of the sentiment/mood (0-100).
     */
    private Integer moodScore;

    public Entry() {
    }

    /**
     * Constructor for creating a new entry with the current date.
     * 
     * @param content The text content of the journal entry.
     */
    public Entry(String content) {
        this.content = content;
        this.entryDate = LocalDate.now();
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public LocalDate getEntryDate() {
        return entryDate;
    }

    public void setEntryDate(LocalDate entryDate) {
        this.entryDate = entryDate;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getAiFeedback() {
        return aiFeedback;
    }

    public void setAiFeedback(String aiFeedback) {
        this.aiFeedback = aiFeedback;
    }

    public Integer getMoodScore() {
        return moodScore;
    }

    public void setMoodScore(Integer moodScore) {
        this.moodScore = moodScore;
    }
}
